# travis-ci.org
#
language: cpp
dist: trusty
compiler:
        - clang
        - gcc
os:
        - linux
before_install:
        - echo $LANG
        - echo $LC_ALL
        - ./scripts/install-dependencies.sh
before_script:
        - mkdir build
        - cd build
        - cmake ../
script:
        - cd build
        - make
branches:
        - master
env:
        global:
                - LANG="en_US.UTF-8"

